### ISSUE TITLE
Adding UISwitch and UIDatePicker

### ISSUE THREAD

**Issue by jaytrisw** [loryhuz/CleanyModal#4]
Hey, love this framework.  I am attempting to add a UISwitch and UIDatePicker to the alert, is this possible?

I am quite new to swift, and I imagine it's something simple that I have overlooked.

Thanks,
Josh

**Comment by loryhuz** [comment]
Hello ! Nice to hear :) 

The most easy way is by calling `alert.addCustomViewInContentStack(yourCustomView)` but I just figured it wasn't working when added before the alert is presented. I'll fix it asap ! 

But you still can subclass CleanyAlertViewController like in the example target, and add your custom view in the stackView by overriding viewDidLoad ;)

**Comment by loryhuz** [comment]
addCustomViewInContentStack has been fixed
