### ISSUE TITLE
Caught an error while compiling 

### ISSUE THREAD

**Issue by arishanapalli** [loryhuz/CleanyModal#6]
caught an error while compiling for the following configuration X-Code Version 10.1 (10B61) Swift 4.2

Error Message
Generic parameter 'T' could not be inferred      

  if #available(iOS 13.0, *) {
            styleSettings.set(key: .textColor, value: .label)
            styleSettings.set(key: .defaultActionColor, value: .label)
            styleSettings.set(key: .destructiveColor, value: .systemRed)
            styleSettings.set(key: .tintColor, value: .systemBlue)
        } 

Can you let me know how can able to fix this following in swift 4.2

**Comment by loryhuz** [comment]
Thanks, I need to check, it's actually built on Swift 5, never tried lower version.

**Comment by loryhuz** [comment]
@arishanapalli I added support for Swift 4.2 in _1.0.1_.

Tell me if all is right for you then. 
Thanks
